name: Publish Package to npm

# Trigger this workflow whenever a new release is published
on:
  release:
    types: [published]

# Grant write permissions to the repository contents so we can push version updates
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    
    steps:
      # Step 1: Check out the repository's code at the default branch
      # This makes your code available for subsequent steps like installing dependencies and running tests.
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 修正: リリースされたタグのコードをチェックアウトする
          ref: ${{ github.ref }}

      # Step 2: Set up a Node.js environment (Node 22.x) and configure npm to use the official registry
      # This ensures we have the right Node.js version and a proper registry URL for installs and publishing.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      # Step 3: Install dependencies using npm ci
      # This ensures a clean, reproducible installation based on package-lock.json.
      - name: Install dependencies
        run: npm ci

      # Step 4: Build
      - name: Build package
        run: npm run build

      # Step 5: Publish the new version to npm
      # The NODE_AUTH_TOKEN is your npm access token stored as a secret.
      # npm publish --access public makes the package available to anyone on npm.
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
